### ISSUE TITLE
Non performant implementation algorithm

### ISSUE THREAD

**Issue by bermuda-sunfish** [wackywendell/primes#4]
The underlying implementation relies on the trial division method rather than the genuine Sieve of Eratosthenes (which the comments in the code seem to imply). 
See https://www.semanticscholar.org/paper/The-Genuine-Sieve-of-Eratosthenes-O%27Neill/ff63a2b396b001d921dc593c4249d74c1b96ec5b for background.

**Comment by wackywendell** [comment]
Wow, that was an interesting read... and I had no idea. For fun, I went ahead and implemented with the Sieve method, so now it actually is that - and added some benchmarks; the Sieve method as I implemented it seems to be about 50-100% faster than the trial division method here.

Thanks for pointing this out! I'm going to close for now, but feel free to reopen if there's more to this!

**Comment by EMBradley** [comment]
When I run the benchmark provided in the repository, I find that the current implementation of `Sieve` is 50-100% _slower_ than `TrialDivision`. I've submitted a pull request that changes `Sieve` to store `Wheel`s in its heap, which allows it to check fewer elements and, more importantly, rearrange the heap far less. This makes `Sieve` roughly 4x faster than `TrialDivision` and nearly 8x faster than its current implementation.
